# Generated by Django 4.2.4 on 2023-08-16 14:58

from django.db import migrations, models
import shortuuid.main


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0023_customer_password_alter_customer_checkid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='checkId',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, max_length=25, unique=True, verbose_name='Check Id'),
        ),
        migrations.AlterField(
            model_name='productpurchase',
            name='duration',
            field=models.FloatField(default=8, verbose_name='Davomiyligi'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productpurchase',
            name='finishedAt',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Tugash sanasi'),
        ),
    ]
