# Generated by Django 4.2.4 on 2023-08-17 20:52

from django.db import migrations, models
import shortuuid.main


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0026_alter_customer_checkid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='checkId',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, max_length=25, unique=True, verbose_name='Check Id'),
        ),
        migrations.AlterField(
            model_name='productpurchase',
            name='duration',
            field=models.IntegerField(verbose_name='Davomiyligi'),
        ),
        migrations.AlterField(
            model_name='productpurchase',
            name='startingFee',
            field=models.IntegerField(default=0.0, verbose_name="Boshlang'ich to'lov"),
        ),
        migrations.AlterField(
            model_name='productpurchase',
            name='taxRate',
            field=models.IntegerField(default=0, verbose_name='Soliq foizi'),
        ),
    ]
