# Generated by Django 4.2.4 on 2023-08-19 10:32

from django.db import migrations, models
import shortuuid.main


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0030_customer_groups_customer_is_active_customer_is_staff_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='showedPassword',
            field=models.CharField(default='Das', max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customer',
            name='checkId',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, max_length=25, unique=True, verbose_name='Check Id'),
        ),
    ]
